[[hypermedia]]
= REST Design - Hypermedia


[#162]
== {MUST} use REST maturity level 2

We strive for a good implementation of
http://martinfowler.com/articles/richardsonMaturityModel.html#level2[REST
Maturity Level 2] as it enables us to build resource-oriented APIs that
make full use of HTTP verbs and status codes. You can see this expressed
by many rules throughout these guidelines, e.g.:

* <<138>>
* <<141>>
* <<148>>
* <<150>>

Although this is not HATEOAS, it should not prevent you from designing
proper link relationships in your APIs as stated in rules below.


[#163]
== {SHOULD} use REST maturity level 3 - HATEOAS

We do recommend to implement
http://martinfowler.com/articles/richardsonMaturityModel.html#level3[REST
Maturity Level 3].

In a distributed system it is really helpful to leave the responsibilty of referencing
related resources to the resource itself.
It helps with code isolation as well as service isolation. Rather than doing hacks like
_expand, the resource can instead link to the related item without having to have deeper insight
to the specific component.

It gives frontend the opportunity to let the backend service manage what the end user
can and cannot do, simply by building up the actions available via a common structure.

For integrations it opens up to not having to hard code the links
to the related resource but gives the consumer the link it requires to retrieve it.
If one resource ends up morphing into a new resource for whatever reason the URL can change
without having to break each and every client using that specific endpoint.

[#164]
== {MUST} use common hypertext controls

When embedding links to other resources into representations you must use the
common hypertext control object. It contains at least one attribute:

* [[href]]{href}: The URI of the resource the hypertext control is linking to.
  All our API are using HTTP(s) as URI scheme.

In API that contain any hypertext controls, the attribute name {href} is
reserved for usage within hypertext controls.

The schema for hypertext controls can be derived from this model:

[source,yaml]
----
Link:
  type: object
  x-examples:
    example-1:
      href: /users/123
      title: User 123
      description: Go to the user with ID 123
      rel: self
      type: GET
  title: ''
  properties:
    href:
      type: string
      format: uri
      example: 'https://example-api.ist.com/'
    title:
      type: string
    description:
      type: string
    rel:
      type: string
      example: self
    type:
      type: string
      enum:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
      example: GET
  required:
    - href
----

The name of an attribute holding such a `Link` object specifies the
relation between the object that contains the link and the linked resource.
Implementations should use names from the {iana-link-relations}[IANA Link Relation Registry]
whenever appropriate. As IANA link relation
names use hyphen-case notation, while this guide enforces snake_case
notation for attribute names, hyphens in IANA names have to be replaced
with underscores (e.g. the IANA link relation type `version-history`
would become the attribute `version_history`)

Specific link objects may extend the basic link type with additional
attributes, to give additional information related to the linked
resource or the relationship between the source resource and the linked
one.

E.g. a service providing "Person" resources could model a person who is
married with some other person with a hypertext control that contains
attributes which describe the other person (`id`, `name`) but also the
relationship "spouse" between the two persons (`since`):

[source,json]
----
{
  "id": "446f9876-e89b-12d3-a456-426655440000",
  "name": "Peter Mustermann",
  "spouse": {
    "href": "https://...",
    "since": "1996-12-19",
    "id": "123e4567-e89b-12d3-a456-426655440000",
    "name": "Linda Mustermann"
  }
}
----

Hypertext controls are allowed anywhere within a JSON model. While this
specification would allow
http://stateless.co/hal_specification.html[HAL], we actually don't
recommend/enforce the usage of HAL anymore as the structural separation
of meta-data and data creates more harm than value to the
understandability and usability of an API.


[#165]
== {SHOULD} use simple hypertext controls for pagination and self-references

For pagination and self-references a simplified form of the <<164, extensible
common hypertext controls>> should be used to reduce the specification and
cognitive overhead. It consists of a simple URI value in combination with the
corresponding {iana-link-relations}[link relations], e.g. {next}, {prev}, {first},
{last}, or {self}.

See <<164>> and <<161>> for more information and examples.


[#217]
== {MUST} use full, absolute URI for resource identification

Links to other resource must always use full, absolute URI.

*Motivation*: Exposing any form of relative URI (no matter if the relative
URI uses an absolute or relative path) introduces avoidable client side
complexity. It also requires clarity on the base URI, which might not be given
when using features like embedding subresources. The primary advantage of
non-absolute URI is reduction of the payload size, which is better achievable
by following the recommendation to use <<156,gzip compression>>


[#166]
== {MUST} not use link headers with JSON entities

For flexibility and precision, we prefer links to be directly embedded in the
JSON payload instead of being attached using the uncommon link header syntax.
As a result, the use of the {RFC-8288}#section-3[`Link` Header defined by RFC
8288] in conjunction with JSON media types is forbidden.
